### INSERT USER
POST http://localhost:8088/api/v1/users
Content-Type: application/json
Accept: application/json

{
  "username" : "akenozahran",
  "password" : "khilmi123/",
  "name" : "Akeno Zahran Asadel"
}

### LOGIN USER
POST http://localhost:8088/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
  "username" : "akenozahran",
  "password" : "khilmi123/"
}